# Churn Analysis using Artificial Neural Network



We are having the dataset of the bank for the 10000 customers. The Bank is seeing the unsual Churn rate. In the 'Excited' Column there are 2 variables i.e., 1(Churn customer) and 0(non-churn customer).
Your objective is to tell which of the customer is at higher risk of leaving.

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

### Importing the dataset

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[1.0 0.0 1 ... 1 1 101348.88]
 [1.0 0.0 0 ... 0 1 112542.58]
 [1.0 0.0 1 ... 1 0 113931.57]
 ...
 [1.0 0.0 1 ... 0 1 42085.58]
 [0.0 1.0 0 ... 1 0 92888.52]
 [1.0 0.0 1 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [54]:
X[0]

array([1.0, 0.0, 1.0, 1, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  =train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
#apply feature scaling for all the features as it is important for the Deep Learning
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
X_train, X_test

(array([[ 0.5698444 , -0.5698444 , -1.01460667, ...,  0.64259497,
         -1.03227043,  1.10643166],
        [-1.75486502,  1.75486502, -1.01460667, ...,  0.64259497,
          0.9687384 , -0.74866447],
        [ 0.5698444 , -0.5698444 ,  0.98560362, ...,  0.64259497,
         -1.03227043,  1.48533467],
        ...,
        [ 0.5698444 , -0.5698444 ,  0.98560362, ...,  0.64259497,
         -1.03227043,  1.41231994],
        [ 0.5698444 , -0.5698444 , -1.01460667, ...,  0.64259497,
          0.9687384 ,  0.84432121],
        [-1.75486502,  1.75486502, -1.01460667, ...,  0.64259497,
         -1.03227043,  0.32472465]]),
 array([[-1.75486502,  1.75486502, -1.01460667, ...,  0.64259497,
          0.9687384 ,  1.61085707],
        [ 0.5698444 , -0.5698444 ,  0.98560362, ...,  0.64259497,
         -1.03227043,  0.49587037],
        [ 0.5698444 , -0.5698444 , -1.01460667, ...,  0.64259497,
          0.9687384 , -0.42478674],
        ...,
        [ 0.5698444 , -0.5698444 , -1.01460667, ...,  

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
#instance of the ANN sequential Class
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
#using dense class for to add a fully connected layer to an ANN
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) 

### Adding the second hidden layer

In [ ]:
#using dense class for to add a fully connected layer to an ANN
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) 

### Adding the output layer

In [ ]:
#at output layer we use sigmoid function
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) 

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [43]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8648
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3290 - accuracy: 0.8651
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8668
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3292 - accuracy: 0.8648
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8654
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8651
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3289 - accuracy: 0.8662
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3292 - accuracy: 0.8631
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3287 - accuracy: 0.8664
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3285 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [55]:
print(ann.predict(ss.transform([[1.0, 0.0, 1,1,0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 31ms/step
[[0.03266388]]


In [58]:
print(ann.predict(ss.transform([[1.0, 0.0, 1,1,0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#0.5 is the threshold value for customer leaving the bank

1/1 [==============================] - 0s 31ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 1, 1, 0" in the first five columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 1, 1 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [60]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100}%\nConfusion matrix: \n{cm}")

Accuracy: 86.15%
Confusion matrix: 
[[1502  184]
 [  93  221]]
